spring:
  application:
    name: certx
  profiles:
    active:
      - dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
server:
  shutdown: graceful

#Actuator
management:
  endpoint:
    restart:
      enabled: true
    health:
      show-details: always

logging:
  file:
    path: logs/
    name: logs/certx.log
  level:
    "[io.github.thirumalx]": debug
  logback:
    rollingpolicy:
      max-history: 10
      max-file-size: 100MB
      total-size-cap: 1GB
