spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/certx
    username: postgres
    password: Thirumal

server:
  port: 8080

certx:
  crypto:
    password-key: YvEj6RT6ZqLfRwV7vVvjSkTpHPrxof+SzCjIMEelwBk=

mail:
  cc: ${MAIL_CC:racetortoise@gmail.com}
  report-to: ${MAIL_REPORT_TO:racetortoise@gmail.com}
